# -*- coding: utf-8 -*-
"""eye_tracking_v1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UGBpj87HVA961Aq1sBF4Kk3yVhRCNTeo
"""

from google.colab import drive
drive.mount('/content/gdrive')

!ls '/content/gdrive/My Drive/RAML/data'

DATA_DIR = '/content/gdrive/My Drive/RAML/data'

import os
os.chdir('/content/gdrive/My Drive/RAML')

!pip install ultralytics

import os
from ultralytics import YOLO

model = YOLO('yolov8l-seg.pt')

model.train(data='/content/gdrive/My Drive/RAML/config.yaml', epochs = 100, imgsz=640)

# resume training

#from ultralytics import YOLO
#model = YOLO()
#model.resume(task='segment')
#resume(model ='/content/gdrive/My Drive/RAML/runs/segment/train/weights/best.pt')

import os
from ultralytics import YOLO


model_path = '/content/gdrive/My Drive/RAML/runs/segment/train/weights/best.pt'
model = YOLO(model_path)

"""## Prediction  """

from ultralytics import YOLO
#model.predict(source='0', stream=True)
model.predict(source='/content/gdrive/My Drive/RAML/eye796.png', save=True, show=True, )

